### ISSUE TITLE
Example with null

### ISSUE THREAD

**Issue by juanitobebe** [Rebilly/ReDoc#415]
Hello,

I have a problem expressing in an example that a property should be null, see:
![image](https://user-images.githubusercontent.com/10404960/36179979-2c68e8e4-10e4-11e8-8f48-2e0c5d0186ca.png)

In the yaml the property is defined as:
```
          previous_page:
             type: number
             x-nullable: true
             description: 'The previous page number.This value is null if there is no previous page to show.'
             example: null
```

We thought that including `x-nullable: true` should be enough.

Is there a workaround for this when using Swagger 2.0 and ReDoc 1.2?

I'll be glad to make that small change in the example renderer if it's needed, I just need someone to shed some light on me.

**Comment by CesarLanderos** [comment]
🙏

**Comment by RomanGotsiy** [comment]
Hey @juanitobebe,
This was an issue of `openapi-sampler` dependency which is used in ReDoc. The issue is already fixed in the latest version `v1.0.0-beta.8` of the sampler so I just updated the dep.

I will release a new patch release `1.20.1` on weekends!

**Comment by juanitobebe** [comment]
Thanks this is great!
We've also been taking a look to 2.0 alpha. It's really good!

**Comment by RomanGotsiy** [comment]
`1.21.0` has been released

**Comment by FoxInFlame** [comment]
This issue still persists with OpenAPI 3.0. I have a string property where I set `nullable` to `true`, and `example` to `null`, yet the ReDoc documentation example shows `"string"`.

**Comment by thanks92** [comment]
> This issue still persists with OpenAPI 3.0. I have a string property where I set `nullable` to `true`, and `example` to `null`, yet the ReDoc documentation example shows `"string"`.

That's true

**Comment by ngthtung** [comment]
Any updates?
