### ISSUE TITLE
Error resolving $ref pointer

### ISSUE THREAD

**Issue by ramsey** [Rebilly/ReDoc#541]
I'm using [speccy](https://github.com/wework/speccy) to resolve separate OpenAPI files into a single file, but while this single file validates and displays properly in the [Swagger Editor](http://editor.swagger.io), ReDoc has problems with it.

## Actual Results

This is the error I'm seeing when trying to load my OpenAPI documentation in ReDoc:

```
Error resolving $ref pointer "https://files.benramsey.com/test/openapi-redoc/openapi.json#/paths/~1user/post/requestBody/content/application~1vnd.example%2Bjson/schema". Token "application/vnd.example%2Bjson" does not exist.
```

<img width="1290" alt="redoc-error" src="https://user-images.githubusercontent.com/42941/41616851-aa2a59c8-73c4-11e8-9051-2fc33173a248.png">

You can see a live example of the error here:
* ReDoc example: <https://files.benramsey.com/test/openapi-redoc/index.html>
* JSON file: <https://files.benramsey.com/test/openapi-redoc/openapi.json>

## Expected Results

I expect to see ReDoc render the documentation, like this: <https://files.benramsey.com/test/openapi-redoc/working.html>.

## Steps To Reproduce

A complete example repository with all the source files and instructions I use to generate them is located here: <https://github.com/ramsey/openapi-redoc-testing>.

### Noteworthy Behavior

In the example repository, if I move the external path schemas (`./openapi/paths/user.yaml` and `./openapi/paths/user-id.yaml`) into the `./openapi/openapi.yaml` file (instead of using `$ref`), then when I resolve it with speccy, ReDoc is properly able to render this.

This working example was produced by moving the external path schemas into the main `openapi.yaml` document:
* Working ReDoc example: <https://files.benramsey.com/test/openapi-redoc/working.html>
* Working JSON file: <https://files.benramsey.com/test/openapi-redoc/openapi-working.json>

---

_It's possible this is an issue with how speccy resolves the paths and not ReDoc, but I've discussed with @philsturgeon, and he recommended I talk to the ReDoc team first to rule it out._

**Comment by RomanGotsiy** [comment]
Thanks again for the detailed issue report!

It seems to be caused by the issue in json-schema-ref-parser. I've opened a PR already: https://github.com/BigstickCarpet/json-schema-ref-parser/pull/90

**Comment by ramsey** [comment]
Thanks for investigating.

I built a new standalone redoc with the commit from your PR here: https://github.com/BigstickCarpet/json-schema-ref-parser/pull/90

Unfortunately, I'm still getting an error, though the error has changed. You can see it here: https://files.benramsey.com/test/openapi-redoc/parser-5fe2988.html

Perhaps I built the standalone version wrong? I changed the dependency in `package.json` to:

```
"json-schema-ref-parser": "git+https://github.com/RomanGotsiy/json-schema-ref-parser.git#5fe2988"
```

And then I ran `npm run bundle` and grabbed the files from the `bundles/` folder.

**Comment by RomanGotsiy** [comment]
Opened one more PR: https://github.com/manuelstofer/json-pointer/pull/30 (which is a dependency of `openapi-sampler` which is a dependency of ReDoc)

I will try to migrate `openapi-sampler` to use `json-schema-ref-parser`'s json pointer resolver to not depend on two libs for the same functionality.

**Comment by RomanGotsiy** [comment]
actually just figured out I was wrong with the PR to json-pointer.
Fixed it directly in `openapi-sampler` and released `1.0.0-beta.13`

**Comment by ramsey** [comment]
Great! That does fix the problem:
https://files.benramsey.com/test/openapi-redoc/redoc-52adc93.html

**Comment by ramsey** [comment]
(together with your PR to `json-schema-ref-parser`, that is)

**Comment by thj-dk** [comment]
When can we expect this to be released? :)

**Comment by RomanGotsiy** [comment]
Once this fix is released https://github.com/Mermade/swagger2openapi/issues/70

**Comment by ramsey** [comment]
It looks like the fix in https://github.com/Mermade/oas-kit/issues/70 is in `swagger2openapi` `v3.0.x`, and ReDoc was updated to `v3.1.2` in e80881f0a834f6b1659c3f2b2f96e3297553b6f2, but even though my example is loading from the CDN (`https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js`), I'm still seeing the same error.

See here: https://files.benramsey.com/test/openapi-redoc/index.html

**Comment by RomanGotsiy** [comment]
Oh, sorry.
It's blocked by https://github.com/BigstickCarpet/json-schema-ref-parser/pull/90 now :(

**Comment by ramsey** [comment]
Thanks!
